lib: [
  "_build/install/default/lib/wordpress_dsl/META" {"META"}
  "_build/install/default/lib/wordpress_dsl/opam" {"opam"}
  "_build/install/default/lib/wordpress_dsl/lib__Config.cmi"
  "_build/install/default/lib/wordpress_dsl/lib__Config.cmx"
  "_build/install/default/lib/wordpress_dsl/lib__Config.cmt"
  "_build/install/default/lib/wordpress_dsl/config.re"
  "_build/install/default/lib/wordpress_dsl/lib.cmi"
  "_build/install/default/lib/wordpress_dsl/lib.cmx"
  "_build/install/default/lib/wordpress_dsl/lib.cmt"
  "_build/install/default/lib/wordpress_dsl/lib.ml-gen"
  "_build/install/default/lib/wordpress_dsl/lib__Theme.cmi"
  "_build/install/default/lib/wordpress_dsl/lib__Theme.cmx"
  "_build/install/default/lib/wordpress_dsl/lib__Theme.cmt"
  "_build/install/default/lib/wordpress_dsl/lib__Theme.cmti"
  "_build/install/default/lib/wordpress_dsl/theme.rei"
  "_build/install/default/lib/wordpress_dsl/lib__Wordpress.cmi"
  "_build/install/default/lib/wordpress_dsl/lib__Wordpress.cmx"
  "_build/install/default/lib/wordpress_dsl/lib__Wordpress.cmt"
  "_build/install/default/lib/wordpress_dsl/lib__Wordpress.cmti"
  "_build/install/default/lib/wordpress_dsl/wordpress.rei"
  "_build/install/default/lib/wordpress_dsl/lib__Wpcli.cmi"
  "_build/install/default/lib/wordpress_dsl/lib__Wpcli.cmx"
  "_build/install/default/lib/wordpress_dsl/lib__Wpcli.cmt"
  "_build/install/default/lib/wordpress_dsl/wpcli.re"
  "_build/install/default/lib/wordpress_dsl/lib.cma"
  "_build/install/default/lib/wordpress_dsl/lib.cmxa"
  "_build/install/default/lib/wordpress_dsl/lib.a"
  "_build/install/default/lib/wordpress_dsl/lib.cmxs"
]
bin: [
  "_build/install/default/bin/hello-wordpress" {"hello-wordpress"}
]
doc: [
  "_build/install/default/doc/wordpress_dsl/README.md"
]
